[build]
  base = "The-Test-Hub /FizzBuzz"         # Correct path to where package.json is located
  publish = "The-Test-Hub /FizzBuzz/dist"  # Folder to publish after npm run build
  command = "npm run build"         # Build command to generate dist/